### ISSUE TITLE
Darko doesn't work in Vertical view

### ISSUE THREAD

**Issue by Tetedeiench** [fastaddons/Darko#10] opened 2020-11-25 16:59 UTC
**Describe the bug**  
When you're using Vertical view, it won't enable unless you switch to Classic view first

**Steps To Reproduce**  
1. Switch to Vertical view ( Customize-> Layout ->Vertical view)
2. Close thunderbird
3. Start thunderbird
5. Emails are still white background even with Darko enabled
6. Switch to "Classic view"
7. It works
8. Switch back to Vertical view
9. It now works until you restart Thunderbird

**Expected behavior**  
The extension should work when installed on a "Vertical layout" Thunderbird without switching to Classic first

**Device info:**
 - operating system: Windows 10
 - Thunderbird : 78.5.0
 - addon version: 2.0 (latest)

**Additional info**
Any restart while in vertical view disables the addon

It's a nice addon, i would keep it if you can fix this annoying bug, as i'm so addicted to the vertical view ;)

**Comment by fastaddons** [comment] 2020-11-25 17:37
Hello,
Thanks for reporting.
This seems to be Thunderbird bug. I can reproduce it in the 78.5.0 but it seems to be working fine in Beta 84.0b2 and Alpha 85.
So hopefully this will be merged to the next 78.6 version.

It's probably this one:
https://bugzilla.mozilla.org/show_bug.cgi?id=1674932
I'll ask there what's the plan.

**Comment by Tetedeiench** [comment] 2020-11-25 19:37
Thanks for the answer ! I'm switching to the latest beta then :)

**Comment by Tetedeiench** [comment] 2020-11-25 19:41
I can confirm, latest beta works fine, thanks !

**Closed as completed** 2021-04-01 07:33 UTC
Labels: bug
